# Config file for automatic testing at travis-ci.com
language: python

python:
  - "3.8"

# # blocklist
# branches:
#   except:
#   - legacy
#   - experimental

# safelist
branches:
  only:
    - main
