name: model-pipeline
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: iterative/setup-cml@v1
      - name: Metrics

        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |     
          echo "# pipeline" > report.md
          cml publish ./images/Speech-to-Text-Architecture.JPG --md >> report.md
          echo "## Model Architecture" >> report.md
          cml publish ./images/RNN_model.png --md >> report.md
          cml send-comment report.md